%% ET4ICP Chapter 6 — Measurement analysis for Group 9
%  Computes:
%   1. Van der Pauw sheet resistances + doping concentrations (Irvin/Masetti)
%   2. ELM sheet resistances + lateral out-diffusion
%   3. NMOS/PMOS Vth + mobility from Id-Vg (max-gm linear extrapolation)
%   4. Vth vs V_T-adjust dose (quadrant sweep) vs Sentaurus simulations
%   5. Id-Vds output characteristics + channel-length modulation
%  All figures land in ../figures, parameters in ../extracted_parameters.txt
clear; close all; clc;

root   = fileparts(mfilename('fullpath'));          % .../chapter06-measurements/matlab
dataD  = fullfile(root, '..', 'IC', 'Group 9');
figD   = fullfile(root, '..', 'figures');
if ~exist(figD, 'dir'), mkdir(figD); end
outTxt = fullfile(root, '..', 'extracted_parameters.txt');
fid    = fopen(outTxt, 'w');
logf   = @(varargin) cellfun(@(t) fprintf(t, varargin{:}), {1, fid}, 'UniformOutput', false);

K    = pi/log(2);          % VdP correction factor
q    = 1.602176634e-19;    % C
Cox  = 8.8541878128e-12*3.9/100e-9;   % F/m^2 (tox = 100 nm)  = 3.453e-4
CoxC = Cox*1e-4;                       % F/cm^2 = 3.453e-8

% Junction depths from Chapter 3 Sentaurus sims (device_sims/junction_depths.txt)
xj.NW = 2.085e-4;  % cm
xj.SN = 0.537e-4;
xj.SP = 0.594e-4;
% Chapter 4 in-line four-point-probe references (Ω/sq)
ch4.NW = 1488.8; ch4.SN = 57.4; ch4.SP = 510.6;

logf('=========================================================\n');
logf('ET4ICP Chapter 6 analysis — Group 9   (generated by analyze_ch6.m)\n');
logf('=========================================================\n\n');

%% ------------------------------------------------------------------
%  1. VAN DER PAUW
%  R_AB,CD = slope of (V1-V2) vs Iforce;  Rsq = pi/ln2 * R_AB,CD
% -------------------------------------------------------------------
vdp = struct('name', {'NW','SN','SP','IC'}, ...
             'file', {'NW_VDP.csv','SN_VDP.csv','SP_NW_VDP.csv','IC_VDP.csv'});
figure('Visible','off','Position',[0 0 1000 750]);
tl = tiledlayout(2,2,'TileSpacing','compact','Padding','compact');
logf('--- 1. Van der Pauw sheet resistances ---\n');
logf('%-6s %14s %14s %12s\n','layer','R_AB,CD (Ohm)','Rsq (Ohm/sq)','fit R^2');
for k = 1:numel(vdp)
    T  = readtable(fullfile(dataD, vdp(k).file));
    dV = T.V1 - T.V2;  I = T.Iforce;
    p  = polyfit(I, dV, 1);
    Rk = p(1);  Rsq = K*Rk;
    res = dV - polyval(p, I);  r2 = 1 - sum(res.^2)/sum((dV-mean(dV)).^2);
    vdp(k).R = Rk; vdp(k).Rsq = Rsq;
    logf('%-6s %14.4f %14.4f %12.6f\n', vdp(k).name, Rk, Rsq, r2);

    nexttile; plot(I*1e6, dV*1e3, 'o', 'MarkerSize', 4); hold on;
    plot(I*1e6, polyval(p, I)*1e3, 'r-', 'LineWidth', 1.2);
    grid on; xlabel('I_{force} (\muA)'); ylabel('V_1 - V_2 (mV)');
    title(sprintf('%s :  R_{AB,CD} = %.4g \\Omega \\rightarrow R_{sq} = %.4g \\Omega/sq', ...
          vdp(k).name, Rk, Rsq));
end
title(tl, 'Van der Pauw structures — 4-point I/V and linear fits (Group 9, TL quadrant)');
exportgraphics(gcf, fullfile(figD,'vdp_iv_fits.png'), 'Resolution', 180);

% --- Doping concentration via rho = Rsq*xj and Masetti mobility (Irvin) ---
logf('\n--- 1b. Doping concentrations (rho = Rsq*xj, Masetti mobility) ---\n');
logf('%-6s %10s %12s %14s %16s %12s\n','layer','xj (um)','rho (Ohm.cm)','mu (cm^2/Vs)','N (cm^-3)','Ch4 N');
layers = {'NW','P' ; 'SN','As' ; 'SP','B'};
ch4N   = [1.5e16, 2e19, 1.5e18];
for k = 1:size(layers,1)
    nm  = layers{k,1};  dop = layers{k,2};
    Rs  = vdp(strcmp({vdp.name}, nm)).Rsq;
    rho = Rs * xj.(nm);                       % Ohm.cm
    f   = @(lgN) rho - 1./(q .* masetti(10.^lgN, dop) .* 10.^lgN);
    lgN = fzero(f, [14 21]);
    N   = 10^lgN;  mu = masetti(N, dop);
    doping.(nm) = N;
    logf('%-6s %10.3f %12.4g %14.1f %16.3g %12.3g\n', nm, xj.(nm)*1e4, rho, mu, N, ch4N(k));
end
% metal sanity check
RsIC = vdp(strcmp({vdp.name},'IC')).Rsq;
logf('IC metal: Rsq = %.4f Ohm/sq -> rho = Rsq*d = %.3g Ohm.cm (d = 0.2 um Al/1%%Si, lit. ~2.7-3.2e-6)\n', ...
     RsIC, RsIC*0.2e-4);

%% ------------------------------------------------------------------
%  2. ELM — electrical line width
%  R from (VH-VL) vs Iforce.  L = 206 um.  Apparent Rsq = R*W/L.
%  Conductance fit: 1/R = (W + 2*dW)/(Rsq*L)  ->  slope & x-intercept
% -------------------------------------------------------------------
L_elm = 206;                       % um
Ws    = [2 5 10];                  % drawn widths, um
lays  = {'NW','SN'};
logf('\n--- 2. ELM structures (L = 206 um) ---\n');
logf('%-4s %6s %14s %18s\n','lay','W(um)','R (Ohm)','Rsq,app (Ohm/sq)');
Rel = struct();
for il = 1:2
    lay = lays{il};
    for iw = 1:3
        T  = readtable(fullfile(dataD, sprintf('ELM_%s_%dum.csv', lay, Ws(iw))));
        dV = T.VH - T.VL;  I = T.Iforce;
        p  = polyfit(I, dV, 1);
        Rel.(lay)(iw) = p(1);
        logf('%-4s %6d %14.2f %18.3f\n', lay, Ws(iw), p(1), p(1)*Ws(iw)/L_elm);
    end
end

% conductance fit -> Rsq_ELM and lateral out-diffusion dW
logf('\n%-4s %16s %14s %12s\n','lay','Rsq_ELM (Ohm/sq)','dW (um)','fit R^2');
figure('Visible','off','Position',[0 0 1100 420]);
tiledlayout(1,2,'TileSpacing','compact','Padding','compact');
for il = 1:2
    lay = lays{il};
    G   = 1./Rel.(lay);
    p   = polyfit(Ws, G, 1);
    RsqE = 1/(p(1)*L_elm);
    dW   = p(2)/(2*p(1));
    res  = G - polyval(p,Ws); r2 = 1 - sum(res.^2)/sum((G-mean(G)).^2);
    elm.(lay).Rsq = RsqE;  elm.(lay).dW = dW;
    logf('%-4s %16.2f %14.3f %12.6f\n', lay, RsqE, dW, r2);

    nexttile;
    Wfit = linspace(-2*dW-0.5, 11, 100);
    plot(Ws, G*1e3, 'bo', 'MarkerSize', 7, 'LineWidth', 1.4); hold on;
    plot(Wfit, polyval(p,Wfit)*1e3, 'r-', 'LineWidth', 1.2);
    xline(-2*dW, 'k--'); yline(0, 'k-');
    text(-2*dW, max(G*1e3)*0.45, sprintf('  -2\\DeltaW = %.2f \\mum', -2*dW), 'Rotation', 90);
    grid on; xlabel('drawn width W (\mum)'); ylabel('conductance 1/R (mS)');
    title(sprintf('%s :  R_{sq} = %.1f \\Omega/sq,  \\DeltaW = %.2f \\mum', lay, RsqE, dW));
end
sgtitle('ELM conductance vs drawn width — lateral out-diffusion extraction');
exportgraphics(gcf, fullfile(figD,'elm_deltaW_fit.png'), 'Resolution', 180);

% apparent Rsq vs width with VdP reference
figure('Visible','off','Position',[0 0 1100 420]);
tiledlayout(1,2,'TileSpacing','compact','Padding','compact');
for il = 1:2
    lay  = lays{il};
    RsV  = vdp(strcmp({vdp.name}, lay)).Rsq;
    Rapp = Rel.(lay).*Ws/L_elm;
    Rcor = Rel.(lay).*(Ws + 2*elm.(lay).dW)/L_elm;
    nexttile;
    plot(Ws, Rapp, 'bo-', 'LineWidth', 1.4, 'MarkerSize', 7); hold on;
    plot(Ws, Rcor, 'ms-', 'LineWidth', 1.2, 'MarkerSize', 7);
    yline(RsV, 'r--', sprintf('VdP  %.1f \\Omega/sq', RsV), 'LineWidth', 1.2);
    grid on; xlabel('drawn width W (\mum)'); ylabel('R_{sq} (\Omega/sq)');
    legend('apparent  R\cdotW_{drawn}/L', 'corrected  R\cdot(W+2\DeltaW)/L', 'Location','southeast');
    title(sprintf('%s sheet resistance vs line width', lay));
end
sgtitle('ELM apparent sheet resistance — effect of lateral out-diffusion');
exportgraphics(gcf, fullfile(figD,'elm_rsq_vs_width.png'), 'Resolution', 180);

%% ------------------------------------------------------------------
%  3. MOSFET transfer characteristics  (VD = +/-0.1 V, linear region)
%  Vth: linear extrapolation at max gm (Vth = Vg* - Id*/gm - VDS/2)
%  mu : gm_max / (Cox * W/L * |VDS|)
% -------------------------------------------------------------------
geo = struct('tag', {'20_1','20_2','20_5','20_10','60_2'}, ...
             'W',   {20, 20, 20, 20, 60}, ...
             'L',   {1, 2, 5, 10, 2});
types = {'NMOS', 'PMOS'};
logf('\n--- 3. Transfer characteristics @ 9e11 quadrant (VD = +/-0.1 V) ---\n');
logf('%-5s %-6s %5s %12s %14s %16s\n','type','W:L','W/L','Vth (V)','gm_max (uS)','mu (cm^2/Vs)');

figure('Visible','off','Position',[0 0 1150 850]);
tlg = tiledlayout(2,2,'TileSpacing','compact','Padding','compact');
mob = struct('NMOS', nan(1,5), 'PMOS', nan(1,5));
vthGeo = struct('NMOS', nan(1,5), 'PMOS', nan(1,5));
cols = lines(5);
for it = 1:2
    typ = types{it};  isP = strcmp(typ,'PMOS');
    axLin = nexttile(it);   hold(axLin,'on');
    axLog = nexttile(it+2); hold(axLog,'on');
    for k = 1:numel(geo)
        if strcmp(geo(k).tag,'20_5')
            f = fullfile(dataD, sprintf('%s_9e11_20_5_Id_Vg.csv', typ));
        else
            f = fullfile(dataD, sprintf('%s_%s_Id_Vg.csv', typ, geo(k).tag));
        end
        T = readtable(f);
        [vg, ix] = sort(T.V_Gate);  id = T.I_Drain(ix);
        VDS = mean(T.V_Drain);
        [vth, gm] = vth_maxgm(vg, id, isP, abs(VDS));
        WL  = geo(k).W/geo(k).L;
        mu  = gm/(CoxC*WL*abs(VDS));          % cm^2/Vs  (gm in S, CoxC in F/cm^2)
        mob.(typ)(k) = mu;  vthGeo.(typ)(k) = vth;
        logf('%-5s %-6s %5.0f %12.3f %14.2f %16.1f\n', typ, ...
             strrep(geo(k).tag,'_',':'), WL, vth, gm*1e6, mu);
        lbl = sprintf('%s  (W/L=%g)', strrep(geo(k).tag,'_',':'), WL);
        plot(axLin, vg, abs(id)*1e6, '-', 'Color', cols(k,:), 'LineWidth', 1.3, 'DisplayName', lbl);
        semilogy(axLog, vg, max(abs(id),1e-13)*1e6, '-', 'Color', cols(k,:), 'LineWidth', 1.3, 'DisplayName', lbl);
    end
    grid(axLin,'on'); grid(axLog,'on');
    xlabel(axLin,'V_G (V)'); ylabel(axLin,'|I_D| (\muA)');
    xlabel(axLog,'V_G (V)'); ylabel(axLog,'|I_D| (\muA)');
    set(axLog,'YScale','log');
    title(axLin, sprintf('%s transfer — linear scale (V_D = %+.1f V)', typ, (1-2*isP)*0.1));
    title(axLog, sprintf('%s transfer — log scale', typ));
    if isP
        legend(axLin, 'Location', 'northeast', 'FontSize', 8);
        legend(axLog, 'Location', 'southwest', 'FontSize', 8);
    else
        legend(axLin, 'Location', 'northwest', 'FontSize', 8);
        legend(axLog, 'Location', 'southeast', 'FontSize', 8);
    end
end
title(tlg, 'I_D–V_G of all geometries, 9\times10^{11} cm^{-2} quadrant (Group 9)');
exportgraphics(gcf, fullfile(figD,'idvg_geometries.png'), 'Resolution', 180);

% mobility / Vth vs channel length summary plot (short-channel physics scales with L)
figure('Visible','off','Position',[0 0 1100 420]);
tiledlayout(1,2,'TileSpacing','compact','Padding','compact');
Ls = [geo.L];
nexttile;
semilogx(Ls, mob.NMOS, 'bo', 'MarkerSize', 9, 'LineWidth', 1.6); hold on;
semilogx(Ls, mob.PMOS, 'rs', 'MarkerSize', 9, 'LineWidth', 1.6);
text(Ls*1.07, mob.NMOS, strrep({geo.tag},'_',':'), 'FontSize', 8, 'Color', 'b');
text(Ls*1.07, mob.PMOS, strrep({geo.tag},'_',':'), 'FontSize', 8, 'Color', 'r');
grid on; xlabel('channel length L (\mum)'); ylabel('\mu (cm^2/V\cdots)');
xlim([0.7 15]);
legend('\mu_n (NMOS)','\mu_p (PMOS)','Location','northeast');
title('Extracted mobility vs channel length');
nexttile;
semilogx(Ls, vthGeo.NMOS, 'bo', 'MarkerSize', 9, 'LineWidth', 1.6); hold on;
semilogx(Ls, abs(vthGeo.PMOS), 'rs', 'MarkerSize', 9, 'LineWidth', 1.6);
text(Ls*1.07, vthGeo.NMOS, strrep({geo.tag},'_',':'), 'FontSize', 8, 'Color', 'b');
text(Ls*1.07, abs(vthGeo.PMOS), strrep({geo.tag},'_',':'), 'FontSize', 8, 'Color', 'r');
grid on; xlabel('channel length L (\mum)'); ylabel('|V_{th}| (V)');
xlim([0.7 15]);
legend('NMOS','|PMOS|','Location','east');
title('Extracted V_{th} vs channel length — roll-off at L = 1 \mum');
sgtitle('Geometry dependence of extracted parameters (9\times10^{11} quadrant)');
exportgraphics(gcf, fullfile(figD,'mu_vth_vs_geometry.png'), 'Resolution', 180);

%% ------------------------------------------------------------------
%  4. Vth vs V_T-adjust dose (20:5 in each quadrant)
% -------------------------------------------------------------------
% NOTE: PMOS_3e11_20_5_Id_Vg.csv is Group 14's bottom-left measurement. Our own
% sweep of that die (quarantined in IC/group_9_problematic/) read Vth = -2.93 V,
% ~0.6 V off the 5-group consensus — a die at the quadrant boundary. See the
% README in that folder.
doses  = [0 3e11 6e11 9e11];
dtag   = {'0e11','3e11','6e11','9e11'};
logf('\n--- 4. Vth vs V_T-adjust dose (20:5) ---\n');
logf('%-10s %12s %12s\n','dose','NMOS Vth(V)','PMOS Vth(V)');
vthQ = struct('NMOS', nan(1,4), 'PMOS', nan(1,4));
figure('Visible','off','Position',[0 0 1150 420]);
tiledlayout(1,2,'TileSpacing','compact','Padding','compact');
for it = 1:2
    typ = types{it}; isP = strcmp(typ,'PMOS');
    ax = nexttile; hold(ax,'on'); cq = lines(4);
    for k = 1:4
        T = readtable(fullfile(dataD, sprintf('%s_%s_20_5_Id_Vg.csv', typ, dtag{k})));
        [vg, ix] = sort(T.V_Gate);  id = T.I_Drain(ix);
        vthQ.(typ)(k) = vth_maxgm(vg, id, isP, abs(mean(T.V_Drain)));
        plot(ax, vg, abs(id)*1e6, '-', 'Color', cq(k,:), 'LineWidth', 1.4, ...
             'DisplayName', sprintf('%s cm^{-2}', strrep(dtag{k},'e11','\times10^{11}')));
    end
    grid on; xlabel('V_G (V)'); ylabel('|I_D| (\muA)');
    title(sprintf('%s 20:5 transfer per quadrant', typ));
    if isP, legend('Location','northeast'); else, legend('Location','northwest'); end
end
sgtitle('Influence of the V_T-adjust dose on the 20:5 transfer characteristics');
exportgraphics(gcf, fullfile(figD,'idvg_quadrants.png'), 'Resolution', 180);
for k = 1:4
    logf('%-10s %12.3f %12.3f\n', dtag{k}, vthQ.NMOS(k), vthQ.PMOS(k));
end

% measured vs simulated
simD   = [3e11 6e11 9e11];
simN   = [0.905 1.162 1.385];
simP   = [-4.372 -4.372 -3.907];
consP3 = -3.587;    % mean PMOS Vth at 3e11 of groups 1,10,13,14,15 (sanity ref for swapped-in point)
figure('Visible','off','Position',[0 0 1150 430]);
tiledlayout(1,2,'TileSpacing','compact','Padding','compact');
nexttile;
plot(doses/1e11, vthQ.NMOS, 'bo-', 'LineWidth', 1.6, 'MarkerSize', 8); hold on;
plot(simD/1e11, simN, 'k^--', 'LineWidth', 1.4, 'MarkerSize', 8);
grid on; xlabel('V_T-adjust dose (10^{11} cm^{-2})'); ylabel('V_{th} (V)');
legend('measured (G9, max-g_m)','Sentaurus (const. current)','Location','northwest');
title('NMOS V_{th} vs V_T-adjust dose');
nexttile;
plot(doses/1e11, vthQ.PMOS, 'rs-', 'LineWidth', 1.6, 'MarkerSize', 8); hold on;
plot(simD/1e11, simP, 'k^--', 'LineWidth', 1.4, 'MarkerSize', 8);
plot(3, consP3, 'gp', 'MarkerSize', 13, 'LineWidth', 1.6);
grid on; xlabel('V_T-adjust dose (10^{11} cm^{-2})'); ylabel('V_{th} (V)');
legend('measured (G9)','Sentaurus','other groups mean @3\times10^{11}','Location','southeast');
title('PMOS V_{th} vs V_T-adjust dose');
sgtitle('Threshold voltage across the wafer: measurement vs simulation');
exportgraphics(gcf, fullfile(figD,'vth_vs_dose.png'), 'Resolution', 180);

%% ------------------------------------------------------------------
%  5. Output characteristics Id-Vds (9e11): 20:1 vs 20:5
%  + channel-length modulation lambda from saturation-region slope
% -------------------------------------------------------------------
logf('\n--- 5. Output characteristics: channel-length modulation ---\n');
logf('lambda fit only where saturation is reached: |VDS| > |VG - Vth(geom)| + 0.3 V\n');
logf('%-5s %-5s %8s %16s %14s\n','type','W:L','VG (V)','Idsat,end (uA)','lambda (1/V)');
for it = 1:2
    typ = types{it}; isP = strcmp(typ,'PMOS');
    figure('Visible','off','Position',[0 0 1150 430]);
    tiledlayout(1,2,'TileSpacing','compact','Padding','compact');
    for ig = 1:2
        tag = {'20_1','20_5'}; tagk = tag{ig};
        vthg = vthGeo.(typ)(strcmp({geo.tag}, tagk));   % Vth of this geometry
        T = readtable(fullfile(dataD, sprintf('%s_9e11_%s_Id_Vds.csv', typ, tagk)));
        vgU = unique(T.V_Gate);
        if isP, vgU = sort(vgU, 'descend'); end
        ax = nexttile; hold(ax,'on'); cc = turbo(numel(vgU)+2);
        for iv = 1:numel(vgU)
            m  = T.V_Gate == vgU(iv);
            [vda, ix] = sort(abs(T.V_Drain(m)));  ida = abs(T.I_Drain(m)); ida = ida(ix);
            plot(ax, vda, ida*1e6, '-', 'Color', cc(iv+1,:), 'LineWidth', 1.3, ...
                 'DisplayName', sprintf('V_G = %g V', vgU(iv)));
            % lambda: linear fit of |Id| vs |Vds| in the saturation region
            vdsat = abs(vgU(iv)) - abs(vthg);          % first-order VDsat estimate
            sel   = vda > vdsat + 0.3;
            if vdsat > 0 && nnz(sel) >= 5
                ps  = polyfit(vda(sel), ida(sel), 1);
                lam = ps(1)/ps(2);                     % Id = Id0*(1 + lambda*Vds)
                logf('%-5s %-5s %8g %16.3f %14.4f\n', typ, strrep(tagk,'_',':'), vgU(iv), ...
                     ida(end)*1e6, lam);
            end
        end
        grid on; xlabel('|V_{DS}| (V)'); ylabel('|I_D| (\muA)');
        title(sprintf('%s %s (W/L = %s)', typ, strrep(tagk,'_',':'), ...
              char("20/"+extractAfter(tagk,'_'))));
        legend('Location','northwest','FontSize',7);
    end
    sgtitle(sprintf('%s output characteristics, 9\\times10^{11} quadrant — note the saturation slope of 20:1', typ));
    exportgraphics(gcf, fullfile(figD, sprintf('%s_idvds.png', lower(typ))), 'Resolution', 180);
end

% normalized comparison at one common VG -> shows CLM + velocity saturation
figure('Visible','off','Position',[0 0 1150 430]);
tiledlayout(1,2,'TileSpacing','compact','Padding','compact');
for it = 1:2
    typ = types{it}; isP = strcmp(typ,'PMOS');
    ax = nexttile; hold(ax,'on');
    vgPick = (1-2*isP)*[4 6];   % NMOS: 4,6 V ; PMOS: -4,-6 V
    sty = {'-','--'};
    for ig = 1:2
        tag = {'20_1','20_5'}; tagk = tag{ig}; Lg = [1 5];
        T = readtable(fullfile(dataD, sprintf('%s_9e11_%s_Id_Vds.csv', typ, tagk)));
        for iv = 1:2
            m = abs(T.V_Gate - vgPick(iv)) < 1e-6;
            if ~any(m), continue; end
            [vd, ix] = sort(T.V_Drain(m)); id = T.I_Drain(m); id = id(ix);
            plot(ax, abs(vd), abs(id)*1e6/(20/Lg(ig)), sty{iv}, 'LineWidth', 1.5, ...
                 'DisplayName', sprintf('%s, V_G = %g V', strrep(tagk,'_',':'), vgPick(iv)));
        end
    end
    grid on; xlabel('|V_{DS}| (V)'); ylabel('|I_D| / (W/L)  (\muA)');
    title(sprintf('%s — current normalised by W/L', typ));
    legend('Location','northwest','FontSize',8);
end
sgtitle('W/L-normalised output curves: 20:1 falls below 20:5 (velocity saturation) and tilts (CLM)');
exportgraphics(gcf, fullfile(figD,'idvds_normalized.png'), 'Resolution', 180);

logf('\nNote: the 20:1 devices (esp. PMOS) never truly saturate (punch-through/DIBL),\n');
logf('so their "lambda" values above are fit artefacts, not channel-length modulation.\n');
logf('\nDone. Figures in %s\n', figD);
fclose(fid);
disp('=== analyze_ch6 finished OK ===');

%% ------------------------- local functions -------------------------
function mu = masetti(N, dop)
% Masetti et al. 1983 doping-dependent low-field mobility (cm^2/Vs)
switch dop
    case 'P'   % phosphorus (n)
        mu = 68.5 + (1414-68.5)./(1+(N/9.20e16).^0.711) - 56.1./(1+(3.41e20./N).^1.98);
    case 'As'  % arsenic (n)
        mu = 52.2 + (1417-52.2)./(1+(N/9.68e16).^0.680) - 43.4./(1+(3.43e20./N).^2.00);
    case 'B'   % boron (p)
        mu = 44.9*exp(-9.23e16./N) + 470.5./(1+(N/2.23e17).^0.719) - 29.0./(1+(6.10e20./N).^2.00);
end
end

function [vth, gmmax] = vth_maxgm(vg, id, isP, vds)
% Linear-extrapolation Vth at maximum transconductance, linear region.
% For PMOS the curve is mirrored so the same code applies; vth gets re-mirrored.
if isP, vg = -vg; id = -id; end
gm = gradient(id, vg);                 % central differences
[gmmax, im] = max(gm);
vth = vg(im) - id(im)/gmmax - vds/2;   % -VDS/2: linear-region correction
if isP, vth = -vth; end
end
